spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Lem0nRabbit/spring-cloud-config
          search-paths: respo
          username: Lem0nRabbit
          password: JuanJuan19960416

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/